// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nulktpviajhhsctcjxzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51bGt0cHZpYWpoaHNjdGNqeHpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDE3NjgsImV4cCI6MjA2MDI3Nzc2OH0.y3ODkCHxEx35uMP55Vc21kTQauqyWviPUAFZfMZ3Qx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);